DEFAULT_PII_LABELS: list[str] = [
    "name",
    "first name",
    "last name",
    "dob",
    "age",
    "email address",
    "phone number",
    "ip address",
    "location address",
    "location city",
    "location state",
    "location zip",
    "account number",
    "bank account",
    "credit card",
    "ssn",
    "money",
    "passport number",
    "driver license",
    "username",
    "password",
    "condition",
    "healthcare number",
    "medical code",
]